#!/bin/bash

function configure-zsh() {
  # Lines configured by zsh-newuser-install
  HISTFILE=~/.histfile
  HISTSIZE=10000
  SAVEHIST=100000
  setopt notify
  unsetopt beep
  bindkey -v
  # End of lines configured by zsh-newuser-install
  # The following lines were added by compinstall
  zstyle :compinstall filename '/home/dm/.zshrc'

  autoload -Uz compinit
  compinit
  # End of lines added by compinstall
  source $HOME/.config/shell/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
  source $HOME/.config/shell/zsh-autosuggestions/zsh-autosuggestions.zsh
}

function configure-theme() {
  eval "$(starship init zsh)"
}

function fix-zsh-pastes() {
  # to workaround bug in zsh-autosuggestions where pastes are really slow
  # This speeds up pasting w/ autosuggest
  # https://github.com/zsh-users/zsh-autosuggestions/issues/238
  pasteinit() {
    OLD_SELF_INSERT=${${(s.:.)widgets[self-insert]}[2,3]}
    zle -N self-insert url-quote-magic # I wonder if you'd need `.url-quote-magic`?
  }
  pastefinish() {
    zle -N self-insert $OLD_SELF_INSERT
  }
  zstyle :bracketed-paste-magic paste-init pasteinit
  zstyle :bracketed-paste-magic paste-finish pastefinish
}

function init-shell-aliases() {
  [ -f $HOME/.config/shell/aliases ] && source $HOME/.config/shell/aliases
}

function init-shell-functions() {
  [ -f $HOME/.config/shell/functions ] && source $HOME/.config/shell/functions
}

function init-shell-env() {
  # required to run kitty natively in wayland
  export KITTY_ENABLE_WAYLAND=1

  # pyenv
  export PYENV_ROOT="$HOME/.pyenv"
  export PATH="$PYENV_ROOT/bin:$PATH"
  if command -v pyenv 1>/dev/null 2>&1; then
    eval "$(pyenv init -)"
  fi

  # required to handle go deps issues
  export GOPROXY="https://proxy.golang.org"

  export GOPATH=$HOME/go
  export PATH=$PATH:$GOPATH/bin
  export GO111MODULE=on
  export PATH=$PATH:$HOME/.local/bin
  export PATH=$PATH:$HOME/Library/Python/3.8/bin
  export PATH="$HOME/.poetry/bin:$PATH"
}

function setup-tools() {
  # autocompletion for kubectl
  [ -x "$(command -v kubectl)" ] && source <(kubectl completion zsh)

  [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
  [ -f /usr/share/fzf/shell/key-bindings.zsh ] && source /usr/share/fzf/shell/key-bindings.zsh
  [ -f /usr/lib/python3.7/site-packages/powerline/bindings/zsh/powerline.zsh ] && source /usr/lib/python3.7/site-packages/powerline/bindings/zsh/powerline.zsh

  # also rvm -related - necessary?
  [ -f /home/damien/.rvm/scripts/rvm ] && source /home/damien/.rvm/scripts/rvm

  # Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
  export PATH="$PATH:$HOME/.rvm/bin"

  # nvm stuff
  export NVM_DIR="$HOME/.nvm"
  [ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

  # Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
  export PATH="$PATH:$HOME/.rvm/bin"

  # To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
  [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

  #THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
  export SDKMAN_DIR="/home/dm/.sdkman"
  [[ -s "/home/dm/.sdkman/bin/sdkman-init.sh" ]] && source "/home/dm/.sdkman/bin/sdkman-init.sh"
}

function setup-shell() {
  configure-zsh
  configure-theme
  fix-zsh-pastes
  init-shell-aliases
  init-shell-functions
  init-shell-env
  setup-tools
}

setup-shell
